### ISSUE TITLE
Switch to crypto/rand

### ISSUE THREAD

**Issue by ChimeraCoder** [stripe/goforit#8]
Since we're not using fixed seeds in tests, there's no reason no use `math/rand`: https://github.com/stripe/goforit/pull/7

**Comment by bobby-stripe** [comment]
crypto/rand is still significantly slower here than math/rand unfortunately.  In https://github.com/stripe/goforit/pull/43 we moved to using a `sync.Pool` of `*math/rand.Rand` objects _seeded_ from `crypto/rand`: https://github.com/stripe/goforit/blob/master/internal/safepool/rand.go#L11-L18 .  Going to close this for now, as I think we're still years away from Linux's `getrandom` improvements being deployed widely enough to directly use `crypto/rand` here.
